version: "3.7"
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: twitter_sample_dev
      POSTGRES_PASSWORD: pgpass
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    image: "redis:6.2.4-alpine"
    command: redis-server
    ports:
     - 6379:6379