default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: twitter_sample_dev
  username: postgres
  password: pgpass
  host: 127.0.0.1

test:
  <<: *default
  database: twitter_sample_test
  username: postgres
  password: pgpass
  host: 127.0.0.1

production:
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: twitter_sample_production
  username: twitter_sample
  password: <%= ENV['twitter_sample_DATABASE_PASSWORD'] %>
